version: '2'
services:
    site:
        image: docker.pkg.github.com/agpopikov/blog/site:latest
        hostname: site
        restart: always
        container_name: site
        volumes:
            - ./Caddyfile:/etc/Caddyfile
            - .certs:/root/.caddy
        logging:
          driver: json-file
          options:
              max-size: "100m"
              max-file: "25"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - TZ=Europe/Moscow
networks:
    default:
        external:
            name: internal
