version: '2'
services:
    blog:
        image: agpopikov/blog:latest
        hostname: blog
        restart: always
        container_name: blog
        volumes:
            - .certs:/root/.caddy
        logging:
          driver: json-file
          options:
              max-size: "100m"
              max-file: "25"
        environment:
            - TZ=Europe/Moscow
networks:
    default:
        external:
            name: internal
