baseURL = "http://blog.agpopikov.info/"
title = "Yep, it's my blog"
theme = "hermit"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
pygmentsCodefences  = true
pygmentsUseClasses  = true
[author]
    name = "Andrey Popikov"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "A minimal and fast theme for Hugo."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.
  relatedPosts = false  # Add a related content section to all single posts page
  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/agpopikov"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/agpopikov"

  [[params.social]]
    name = "github"
    url = "https://github.com/agpopikov"

[menu]
  [[menu.main]]
    name = "Блог"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Обо мне"
    url = "about/"
    weight = 20
