name: master
on:
  push:
    branches:
      - master
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login hub.docker.com -u agpopikov --password-stdin
      - name: Build site Docker image
        run: |
          docker build . -t hub.docker.com/agpopikov/blog:latest
          docker push hub.docker.com/agpopikov/blog:latest
  deploy-latest:
    runs-on: ubuntu-latest
    needs: build-latest
    steps:
        - uses: actions/checkout@v2
        - name: Run site deploy
          run: |
            mkdir ~/.ssh
            echo "${{ secrets.SITE_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            scp -o StrictHostKeyChecking=no Caddyfile docker-compose.yml root@blog.agpopikov.info:~/apps/site/
            ssh -o StrictHostKeyChecking=no root@blog.agpopikov.info 'cd ~/apps/site && docker-compose pull && docker-compose up -d'
