name: master
on:
  push:
    branches:
      - master
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u agpopikov --password-stdin
      - name: Build site Docker image
        run: |
          docker build . -t docker.pkg.github.com/agpopikov/blog/site:latest
          docker push docker.pkg.github.com/agpopikov/blog/site:latest
  deploy-latest:
    runs-on: ubuntu-latest
    needs: build-latest
    steps:
        - uses: actions/checkout@v2
        - name: Run site deploy
          run: |
            mkdir ~/.ssh
            echo "${{ secrets.SITE_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            scp -o StrictHostKeyChecking=no Caddyfile docker-compose.yml root@blog.agpopikov.info:~/apps/site/
            ssh -o StrictHostKeyChecking=no root@blog.agpopikov.info 'cd ~/apps/site && docker-compose up -d'
